name: build NamelessLibV

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/main.yml'
  pull_request:
    branches:
      - main
      
